import { defineConfig } from "vite";
import laravel from "laravel-vite-plugin";
import tailwindcss from "@tailwindcss/vite";

export default defineConfig({
    plugins: [
        laravel({
            input: [
                // CSS Files
                "resources/css/app.css",
                "resources/css/changePass.css",
                "resources/css/forgot_pass.css",
                "resources/css/header.css",
                "resources/css/healthWorker.css",
                "resources/css/homepage.css",
                "resources/css/logout-on-top.css",
                "resources/css/manageInterface.css",
                "resources/css/navbar.css",
                "resources/css/nurse_dashboard.css",
                "resources/css/patient-list.css",
                "resources/css/pdfTableTemplate.css",
                "resources/css/profile.css",
                "resources/css/auth/login.css",
                "resources/css/auth/registration.css",
                "resources/css/dashboard/pdfGraph.css",
                "resources/css/family-planning/pdf-styles.css",
                "resources/css/heatmap/heat_map.css",
                "resources/css/inventory_system/inventory.css",
                "resources/css/inventory_system/inventory-report.css",
                "resources/css/manageUsers/manageUsers.css",
                "resources/css/masterList/masterlist.css",
                "resources/css/masterList/wra_masterlist.css",
                "resources/css/patient/add-patient.css",
                "resources/css/patient/add-patient-prenatal.css",
                "resources/css/patient/patient-dashboard.css",
                "resources/css/patient/record.css",

                // JS Files
                "resources/js/app.js",
                "resources/js/automateAge.js",
                "resources/js/bootstrap.js",
                "resources/js/changePassword.js",
                "resources/js/header.js",
                "resources/js/healthWorker.js",
                "resources/js/homepage.js",
                "resources/js/interaction.js",
                "resources/js/inventory-report.js",
                "resources/js/login.js",
                "resources/js/menudropdown.js",
                "resources/js/navbar.js",
                "resources/js/passwordReset.js",
                "resources/js/patient-list.js",
                "resources/js/profileInterface.js",
                "resources/js/register.js",
                "resources/js/address/address.js",
                "resources/js/chart/chart.js",
                "resources/js/chart/pdfChart.js",
                "resources/js/dashboard/nurseDashboard.js",
                "resources/js/dashboard/staffDashboard.js",
                "resources/js/datePicker/record.js",
                "resources/js/family_planning/add_patient.js",
                "resources/js/family_planning/case.js",
                "resources/js/family_planning/editFamilyPlanningRadioToggle.js",
                "resources/js/family_planning/editPatientCase.js",
                "resources/js/family_planning/editPatientDetails.js",
                "resources/js/family_planning/familyPlanningRadioToggle.js",
                "resources/js/family_planning/sideB.js",
                "resources/js/heatmap/heat-map.js",
                "resources/js/inventory_system/category.js",
                "resources/js/inventory_system/medicineRequest.js",
                "resources/js/LMP/lmp.js",
                "resources/js/manageInterface/manageInterface.js",
                "resources/js/manageUser/manageUser.js",
                "resources/js/manageUser/userProfile.js",
                "resources/js/masterlist/vaccination.js",
                "resources/js/masterlist/wra.js",
                "resources/js/notification/notification.js",
                "resources/js/patient/add-patient.js",
                "resources/js/patient/editPatientDetails.js",
                "resources/js/patient/healthWorkerList.js",
                "resources/js/patient-case-info/family_plan_side_a.js",
                "resources/js/patient-case-info/family_plan_side_b.js",
                "resources/js/patient-case-info/prenatal_case.js",
                "resources/js/patient-case-info/senior_citizen_case.js",
                "resources/js/patient-case-info/tb_dots_case.js",
                "resources/js/patient-case-info/vaccination_case.js",
                "resources/js/prenatal/addPregnancyPlan.js",
                "resources/js/prenatal/addPrenatalCase.js",
                "resources/js/prenatal/addPrenatalPatient.js",
                "resources/js/prenatal/editPrenatalDetails.js",
                "resources/js/prenatal/familyPlansideA.js",
                "resources/js/prenatal/pregnancyCheckup.js",
                "resources/js/prenatal/prenatalCase.js",
                "resources/js/record/record.js",
                "resources/js/senior_citizen/addCase.js",
                "resources/js/senior_citizen/addPatient.js",
                "resources/js/senior_citizen/caseRecord.js",
                "resources/js/senior_citizen/editPatientDetails.js",
                "resources/js/signature/signature.js",
                "resources/js/tb_dots/addCaseRecord.js",
                "resources/js/tb_dots/add_patient.js",
                "resources/js/tb_dots/caseRecord.js",
                "resources/js/tb_dots/checkup.js",
                "resources/js/tb_dots/editDetails.js",
                "resources/js/vaccination/vaccinationCase.js",
                "resources/js/vitalSign.js",
                "resources/js/add_patient/searchUser.js",
            ],
            refresh: true,
        }),
        tailwindcss(),
    ],
});
